#!/bin/bash
. rvmup

export ZK_HOST="localhost:$(EphemeralPort 2181)"

CONTAINERS=$(docker ps | grep 9092 | awk '{print $1}')
BROKERS=$(for CONTAINER in $CONTAINERS; do docker port $CONTAINER 9092 | sed -e "s/0.0.0.0:/$HOST_IP:/g"; done)
export KAFKA_BROKERS=$(echo "localhost$(echo $BROKERS | sed -e 's/ /,localhost/g')")

echo "ZK_HOST: $ZK_HOST"
echo "KAFKA_BROKERS: $KAFKA_BROKERS"
